#all: # Все серверы в нашем inventory, all - обязателен
#  children: # Дочерние группы для all
#    backend: # Группа хостов с именем backend
#      hosts:
#        158.160.33.197 ansible_ssh_user=ansible ansible_ssh_private_key_file=/home/student/.ssh/id_rsa
#    frontend:
#      hosts:
#        10.66.101.8 ansible_ssh_user=ansible ansible_ssh_private_key_file=/home/student/.ssh/id_rsa
all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_user : ansible 
  children:
    backend:
      hosts:
       test1:
         ansible_host : '158.160.33.197'